services:
  - type: web
    name: frios-uploader
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    runtime: python
    region: oregon
    plan: free
    branch: main
    autoDeploy: true
